### ISSUE TITLE
Move GUI code into seperate file

### ISSUE THREAD

**Issue by alxhoff** [munober/webscrapper#12]

**Comment by alxhoff** [comment]
see [here](https://github.com/alxhoff/BrezeFlow/tree/master/UI)

**Comment by munober** [comment]
okay so I took a look at your UI code, I did the same thing you do in the shell script with converting a .ui file to .py with pyuic5 but only once and manually in the terminal, then refined it by hand, e.g. I added function calls that I couldn't add in the .ui file. We could totally add a script in here too if we want to change the interface later on.

The very specific problem that prevents me from moving the entire Ui_dialog class into a separate .py file are the calls from within it to the different def's I have in scrapper.py, which I do on different .connect's that I attach to buttons and other UI elements, and which don't seem to want to let themselves be called from outside.

Is this the right approach, to hard-code the .connect calls from the UI elements to the def's? Or am I missing something? Can I create some sort of list of links between UI elements and function calls/variable names?

**Comment by alxhoff** [comment]
You can create classes in your code that then load the generated objects. So you should create a folder similar to BrezeFlow like `UI` where the generated files get dumped into then you can create classes that instantiate these UI objects. The UI objects have hardcoded names, but QtDesigner makes sure they are all unique. See [here](https://github.com/alxhoff/BrezeFlow/blob/dc9b6bf8c64ce2d6e1f0e10d5ca02220d1a3f35d/EnergyDebugger.py#L298)

**Comment by munober** [comment]
okay, this might take me a while, but I'll get it

**Comment by alxhoff** [comment]
yer no rush.
