### ISSUE TITLE
Preprocessing fails

### ISSUE THREAD

**Issue by alxhoff** [munober/webscrapper#17]
**Describe the bug**
```
Entering pre-processing mode: will change image size  
Failed to preprocess images: [Errno 2] No such file or directory: './export_preprocessing/cropped'

```

**To Reproduce**
After pulling #15 to fix `FileExistsError: [Errno 17] File exists: './dataset'` preprocessing fails

**Comment by alxhoff** [comment]
Breaks #14

**Comment by munober** [comment]
this should work now too, try it on your system

**Comment by alxhoff** [comment]
Images don't seem to resize.

**Comment by munober** [comment]
mmmm they do on my end :-?
Does this happen when you are passing -pp -w xxx -ht xxx as arguments?

**Comment by alxhoff** [comment]
getting this now
```
Could not load ./export_preprocessing/cropped/Chris_Hemsworth/c8bfe736211.jpg - OpenCV(4.2.0) /io/opencv/modules/imgproc/src/resize.cpp:4048: error: (-215:Assertion failed) inv_scale_x > 0 in function 'resize'
``` 
I will fix it up now

**Comment by munober** [comment]
I never got that error, how are you planning to fix it?

**Comment by alxhoff** [comment]
I had passed width as -80 by accident. Just added an `abs` to avoid doing that again :P
