### ISSUE TITLE
Error not handled elegantly

### ISSUE THREAD

**Issue by alxhoff** [munober/webscrapper#18]
**Describe the bug**
Empty folder in dataset/xxxx/ throws
`Could not load a file - [Errno 20] Not a directory: './dataset/imdbactors.txt'`

**Expected behavior**
Probably need a `try` & `except` placed somewhere where you pass folders in the dataset directory

**Comment by munober** [comment]
yeah, that happens very specifically for this one file that I save under /dataset. I'm thinking maybe just except .txt's? Or just non-picture folders in general?

**Comment by alxhoff** [comment]
Is is not looping over all directories inside `dataset`?

**Comment by munober** [comment]
it is, I added a if isdir: ... at the very top to exclude all that isn't one

**Comment by alxhoff** [comment]
that should fix it

**Comment by munober** [comment]
alright, can I close this then?

**Comment by alxhoff** [comment]
beat you to it

**Comment by munober** [comment]
damn
