### ISSUE TITLE
Image preprocessing

### ISSUE THREAD

**Issue by alxhoff** [munober/webscrapper#5]
**Is your feature request related to a problem? Please describe.**
Not sure if this exists, I didn't really check. 
It would be good to be able to pass in desired image sizes and have the tool scrape, check, and pre-process the images to the right sizes and optionally convert them to grey scale.

**Describe the solution you'd like**
Providing command line arguments such as `-w 32 -g 40 -gs` for a width of 32 and height of 40 with the image being converted to grey-scale. The image should be shrunk and cropped such that the person's face remains in the image, not necessarily centered as variation would be good for training models.

**Comment by munober** [comment]
Not yet, but I could totally do that, would work well together with the filter mode (-f on) which is completely separate from the searching and downloading part.

**Comment by alxhoff** [comment]
yep, search and download -> filter/check -> preprocess

maybe even add the option to zip the final set so it's one file
