### ISSUE TITLE
Input file with list of search terms

### ISSUE THREAD

**Issue by alxhoff** [munober/webscrapper#6]
**Is your feature request related to a problem? Please describe.**
Be able to provide a file with search terms eg.

``` 
brad pitt
sean conery
...
```

**Comment by munober** [comment]
That works already for dataset/imdb_actors.txt, as in it takes the automatically generated list you get by  doing -l or running without no arguments and no pre-existing dataset folder. But yes,  we could totally add a CLI argument for running with a custom provided list.

**Comment by alxhoff** [comment]
yep, just trying to remove all hardcoded stuff. hardcoding is bad :P

**Comment by alxhoff** [comment]
i wouldn't close it until it's done.

**Comment by munober** [comment]
it’s done, latest commit

**Comment by alxhoff** [comment]
ahhh. you can reference issues from commits by putting #6 in the commit message

**Comment by munober** [comment]
will do from now on, didn’t know that xD
