### ISSUE TITLE
Headless google images

### ISSUE THREAD

**Issue by alxhoff** [munober/webscrapper#7]
**Describe the bug**
Headless image scraping using google images failing

**Comment by munober** [comment]
imdb was failing and google worked, on my setup at least

**Comment by alxhoff** [comment]
ahhh so the other way around?

**Comment by munober** [comment]
yes, exactly. like it’s not that it was totally failing but selenium said it found 0 images on the page so it moved on to the next actor and so on

**Comment by alxhoff** [comment]
ok. yer I have a few ideas as well how we can speed it up 1000 fold :P

**Comment by munober** [comment]
what would that look like? 🤯

**Comment by alxhoff** [comment]
you'll have to wait and see :P might find time next week to have a crack at it

**Comment by munober** [comment]
imdb is fixed for good now, as in I gave up on selenium for it completely and i'm only using selenium for google. the pyqt interface is also done

**Comment by alxhoff** [comment]
nice man! I will 100% have time to look at it net week! I will see if I can add some optimizations. Also one of the guys in our group had some luck with im2col. I will share what he has done when I get a chance to look at it.

**Comment by munober** [comment]
all cool, just please give me something else to do now, I’ve had way too much of web scraping. also, when would you have time to get on a call about the thesis?

**Comment by alxhoff** [comment]
hahaha I bet. Next step would be to start looking at building minimal NN models in tensorflow for face detection. You can look at my MNIST one to see how "small" the models should be. The TinyML book talks about parameter count etc and this is exactly what should be kept small. We can have a call next week to talk about your thesis but the first thing for you to do would be to come up with a few rough models that give decent results that we can then use in creating some sort of automated heuristic for optimizing the model's accuracy against the number of parameters.

**Comment by munober** [comment]
great, will start working on that!
